apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend  # This must match the `app: backend` label in your backend deployment
  ports:
    - protocol: TCP
      port: 3001       # Exposed service port
      targetPort: 3001 # Port where the backend container is listening
  type: ClusterIP       # Makes the service accessible only within the cluster
