version: '3'
services:
  backend:
    image: hemanthkolli99/backend
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  frontend:
    image: hemanthkolli99/frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  mongo:
    image: mongo
    ports:
      - "27017:27017"
